### ISSUE TITLE
Plugins saves model resources under wrong name?

### ISSUE THREAD

**Issue by jo-mueller** [bioimage-io/napari-bioimage-io#109]
Hi devs,

when I use the plugin to download the specs of a model from the model zoo, the list of files in the respective directory on my machine looks like this:

![Capture](https://github.com/bioimage-io/napari-bioimageio/assets/38459088/34a7b73b-2167-46cc-87a3-1d6e5c932bc9)

The content of the rdf file also states so so I think that the contents of the model specs somehow get lost in the downloading process. The files are still the correct ones (at least the file sizes line up with the files I get if I download the models from the homepage directly), so I think it's just the naming that's off.

```
authors:
- {affiliation: EMBL, name: Adrian Wolny}
- {affiliation: Heidelberg University, name: Lorenzo Cerrone}
cite:
- {text: 'Wolny, Cerrone et al. Accurate and Versatile 3D Segmentation of Plant Tissues
    at Cellular Resolution. eLife 2020.', url: 'https://elifesciences.org/articles/57613'}
config:
  bioimageio:
    created: '2023-04-06 12:43:33.436336'
    doi: 10.5281/zenodo.7805434
    nickname: passionate-t-rex
    nickname_icon: "\U0001F996"
    owners: [66700]
    status: accepted
    version_id: '7805434'
    version_name: version 6
covers: [content-2, content-3, content-4]
description: 'A 3d U-Net trained to predict the cell boundaries in confocal stacks
  of Arabidopsis ovules. Voxel size: (0.235, 0.150, 0.150) microns ZYX'
documentation: content-5
format_version: 0.4.9
id: 10.5281/zenodo.6334583/7805434
inputs:
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: input0
  shape: [1, 1, 100, 128, 128]
license: MIT
links: [imjoy/BioImageIO-Packager]
maintainers:
- {github_user: wolny, name: Adrian Wolny}
name: 3D UNet Arabidopsis Ovules
outputs:
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: output0
  shape: [1, 1, 100, 128, 128]
rdf_source: https://bioimage-io.github.io/collection-bioimage-io/rdfs/10.5281/zenodo.6334583/7805434/rdf.yaml
tags: [3d, torchscript, ilastik, unet, plant, plantseg, cell-membrane, ovules, tissue,
  semantic-segmentation, arabidopsis, deepimagej, pytorch, fluorescence-light-microscopy]
test_inputs: [content-6]
test_outputs: [content-7]
timestamp: '2023-04-06T14:04:23.266519'
type: model
version: 0.1.0
weights:
  pytorch_state_dict:
    architecture: content:UNet3D
    architecture_sha256: 2da9f7149e144b63fee715fb8fe5154e96bf9aa230d176c91e923d528ef0c4e1
    kwargs: {f_maps: 32, final_sigmoid: true, in_channels: 1, is_segmentation: true,
      layer_order: gcr, num_groups: 8, out_channels: 1}
    sha256: 0f11cbd0608d12ef161892586408c6ec1a074f1f27ea6afef9d1ceece3dd3c1f
    source: content-0
  torchscript: {pytorch_version: 2.0.0, sha256: 09be0d33ca00fb8137cca507a69f5e95719a159ada0d709286ae9dc183093aaf,
    source: content-1}
```
